/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- Find total customers by countries
SELECT
    Country,
    COUNT (customer_key) AS total_customer 
FROM customers
GROUP BY Country
ORDER BY total_customer DESC;


-- Find total customers by gender
SELECT
    gender,
    COUNT (customer_key) AS total_customer
FROM customers
GROUP BY gender
ORDER BY total_customer DESC;

-- Find total products by category
SELECT
    category,
    COUNT (product_key) AS total_products
FROM Products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category
SELECT 
    category,
    AVG (cost) AS avg_cost
FROM Products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category
SELECT
    p.category,
    SUM (s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Find total revenue is generated by each customers
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM (s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN customers c
ON c.customer_key = s.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- What is the distribution of sold items across countries
SELECT
    c.country,
    SUM (s.quantity) AS total_sold_item
FROM sales s
LEFT JOIN customers c
ON c.customer_key = s.customer_key
GROUP BY
    c.country
ORDER BY total_sold_item DESC;